table customer_churn_test_predictions
	lineageTag: 3e58cc79-4ffa-47f1-aa82-5479ee7fab68
	sourceLineageTag: [dbo].[customer_churn_test_predictions]

	measure 'Churn Rate' = AVERAGE(customer_churn_test_predictions[predictions])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2ec64d3f-717d-406b-b8f3-5cd4f81b179d

		changedProperty = Name

		changedProperty = FormatString

	measure Customers = COUNT(customer_churn_test_predictions[predictions])
		formatString: 0
		lineageTag: 903d2b6e-0dc5-4ae6-828e-74b0c2f2adca

		changedProperty = Name

	measure 'Germany Churn' = CALCULATE(AVERAGE(customer_churn_test_predictions[predictions]),FILTER(customer_churn_test_predictions, customer_churn_test_predictions[Geography_Germany] = TRUE()))
		lineageTag: 3cab46b8-5407-4ed5-897c-c829e8700b1e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Spain Churn' = CALCULATE(AVERAGE(customer_churn_test_predictions[predictions]),FILTER(customer_churn_test_predictions, customer_churn_test_predictions[Geography_Spain] = TRUE()))
		lineageTag: 214dcb70-5cb5-4b06-86a9-e3608f317b1b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'France Churn' = CALCULATE(AVERAGE(customer_churn_test_predictions[predictions]),FILTER(customer_churn_test_predictions, customer_churn_test_predictions[Geography_France] = TRUE()))
		lineageTag: d33f72fa-94ce-4c5d-ad93-44e1198c1642

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditScore
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3f4caf81-91e9-4859-91fa-4f420aefd890
		sourceLineageTag: CreditScore
		summarizeBy: sum
		sourceColumn: CreditScore

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a7a47c17-df71-4efe-9a13-5ea58dfe735b
		sourceLineageTag: Age
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Tenure
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 31d8f784-1a6b-4e75-b9cb-6c12c74786b6
		sourceLineageTag: Tenure
		summarizeBy: sum
		sourceColumn: Tenure

		annotation SummarizationSetBy = Automatic

	column Balance
		dataType: double
		sourceProviderType: float
		lineageTag: 8deda794-b714-4cbb-93fd-aebed578399e
		sourceLineageTag: Balance
		summarizeBy: sum
		sourceColumn: Balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumOfProducts
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f46d710a-9b96-41ab-9bab-fa01caee6e73
		sourceLineageTag: NumOfProducts
		summarizeBy: sum
		sourceColumn: NumOfProducts

		annotation SummarizationSetBy = Automatic

	column HasCrCard
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 38703828-6f03-49d9-bf7a-eada25e53219
		sourceLineageTag: HasCrCard
		summarizeBy: sum
		sourceColumn: HasCrCard

		annotation SummarizationSetBy = Automatic

	column IsActiveMember
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1fe38be7-ff84-487d-90ff-ae4d0d8980ce
		sourceLineageTag: IsActiveMember
		summarizeBy: sum
		sourceColumn: IsActiveMember

		annotation SummarizationSetBy = Automatic

	column EstimatedSalary
		dataType: double
		sourceProviderType: float
		lineageTag: 88725e3c-ea79-47af-a33e-06af136745a1
		sourceLineageTag: EstimatedSalary
		summarizeBy: sum
		sourceColumn: EstimatedSalary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NewTenure
		dataType: double
		sourceProviderType: float
		lineageTag: 907c30ca-a691-48f3-8122-359322c6c1bd
		sourceLineageTag: NewTenure
		summarizeBy: sum
		sourceColumn: NewTenure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NewCreditsScore
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b2caac85-687f-48d5-aa45-ccf3abe0bbca
		sourceLineageTag: NewCreditsScore
		summarizeBy: sum
		sourceColumn: NewCreditsScore

		annotation SummarizationSetBy = Automatic

	column NewAgeScore
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5d8c1fa5-9da4-4ea1-8bc7-dedcd6baa7a6
		sourceLineageTag: NewAgeScore
		summarizeBy: sum
		sourceColumn: NewAgeScore

		annotation SummarizationSetBy = Automatic

	column NewBalanceScore
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 529405f1-4669-4a80-ad36-7856c6862098
		sourceLineageTag: NewBalanceScore
		summarizeBy: sum
		sourceColumn: NewBalanceScore

		annotation SummarizationSetBy = Automatic

	column NewEstSalaryScore
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4b74e928-437c-40ff-98a3-628aac2d9142
		sourceLineageTag: NewEstSalaryScore
		summarizeBy: sum
		sourceColumn: NewEstSalaryScore

		annotation SummarizationSetBy = Automatic

	column Geography_France
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 3e22e745-5632-46a2-943c-4ab8b8417c53
		sourceLineageTag: Geography_France
		summarizeBy: none
		sourceColumn: Geography_France

		annotation SummarizationSetBy = Automatic

	column Geography_Germany
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 0ec49e46-8a3a-4139-8787-1323e8b72397
		sourceLineageTag: Geography_Germany
		summarizeBy: none
		sourceColumn: Geography_Germany

		annotation SummarizationSetBy = Automatic

	column Geography_Spain
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: ddaf2ef1-39e5-4979-b9d1-cb2a294fed48
		sourceLineageTag: Geography_Spain
		summarizeBy: none
		sourceColumn: Geography_Spain

		annotation SummarizationSetBy = Automatic

	column Gender_Female
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 21280d6c-71c2-4dd6-ab97-8bd94c17e027
		sourceLineageTag: Gender_Female
		summarizeBy: none
		sourceColumn: Gender_Female

		annotation SummarizationSetBy = Automatic

	column Gender_Male
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 58cbb2cf-ecb3-4e4a-9745-cdc43fa157d8
		sourceLineageTag: Gender_Male
		summarizeBy: none
		sourceColumn: Gender_Male

		annotation SummarizationSetBy = Automatic

	column predictions
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ac1839df-93b9-4997-9c07-844ffa55926b
		sourceLineageTag: predictions
		summarizeBy: sum
		sourceColumn: predictions

		annotation SummarizationSetBy = Automatic

	partition customer_churn_test_predictions = entity
		mode: directLake
		source
			entityName: customer_churn_test_predictions
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

